include dracula.conf

font_family CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14
bell_type none

confirm_os_window_close 0
scrollback_lines 100000
enable_audio_bell no
window_margin_width 4

enabled_layouts splits

map cmd+h previous_tab
map cmd+l next_tab
map cmd+j previous_tab
map cmd+k next_tab

map cmd+b launch --location=vsplit

map cmd+w close_window_with_confirmation ignore-shell
confirm_os_window_close -1
